In [1]:
import gym

env = gym.make('CartPole-v1')
env = gym.make("CartPole-v1", render_mode="rgb_array")

In [2]:
state = env.reset()
print(state)

action_space = env.action_space
print(action_space)

(array([-0.03573466,  0.02345425, -0.04693706, -0.01173813], dtype=float32), {})
Discrete(2)


In [3]:
action = 0
next_state, reward, done, info, info1 = env.step(action)
print(next_state)

[-0.03526557 -0.17096423 -0.04717182  0.26577398]


In [4]:
output = env.step(action)
print(output)


(array([-0.03868486, -0.36538228, -0.04185634,  0.5432133 ], dtype=float32), 1.0, False, False, {})


In [17]:
import numpy as np
import gym
import time

env = gym.make('CartPole-v0',render_mode='human')
state = env.reset()
done = False


time.sleep(0.5)
while not done:
    time.sleep(0.05)
    env.render()
    action = np.random.choice([0, 1])
    next_state, reward, done, info, info1 = env.step(action)
env.close()

In [10]:
import numpy as np
import gym

env = gym.make('CartPole-v0', render_mode = 'human')    # Cartpole定義
env.reset()    # Cartpoleの状態初期化

for i in range(1000):
    env.render()    # Cartpoleのアニメーション
    observation, reward, done, info, info1 = env.step(env.action_space.sample())  # カートを動かし、結果を返す
    print("Step:",i,done,"Reward:",reward,"Obs:",observation)

Step: 0 False Reward: 1.0 Obs: [ 0.01443197  0.22822258 -0.03508245 -0.349859  ]
Step: 1 False Reward: 1.0 Obs: [ 0.01899642  0.03361668 -0.04207963 -0.06844189]
Step: 2 False Reward: 1.0 Obs: [ 0.01966876  0.22931588 -0.04344847 -0.37409857]
Step: 3 False Reward: 1.0 Obs: [ 0.02425507  0.4250272  -0.05093044 -0.6801584 ]
Step: 4 False Reward: 1.0 Obs: [ 0.03275562  0.2306483  -0.06453361 -0.40393513]
Step: 5 False Reward: 1.0 Obs: [ 0.03736858  0.0364981  -0.07261231 -0.13227578]
Step: 6 False Reward: 1.0 Obs: [ 0.03809855  0.232581   -0.07525782 -0.44695434]
Step: 7 False Reward: 1.0 Obs: [ 0.04275017  0.42868242 -0.08419691 -0.7623788 ]
Step: 8 False Reward: 1.0 Obs: [ 0.05132382  0.62485695 -0.09944449 -1.0803229 ]
Step: 9 False Reward: 1.0 Obs: [ 0.06382096  0.8211411  -0.12105095 -1.402483  ]
Step: 10 False Reward: 1.0 Obs: [ 0.08024377  0.62771297 -0.1491006  -1.149966  ]
Step: 11 False Reward: 1.0 Obs: [ 0.09279804  0.8244324  -0.17209992 -1.4854447 ]
Step: 12 False Reward: 1.0

KeyboardInterrupt: 